#!/usr/bin/env node
const fs = require('fs');

const msg = fs.readFileSync(process.argv[2], 'utf-8').trim(); // 索引 2 对应的 commit 消息文件
const commitRE = /^(feat|fix|docs|style|refactor|test|workflow|build|ci|chore|release)(\(.+\))?: .{1,100}/;

if (!commitRE.test(msg)) {
  console.log();
  console.error('不合法的 commit 消息格式，请使用正确的提交格式：');
  console.error('详情请查看 git commit 提交规范：https://www.yuque.com/webknowledge/document/ypa5ug#HivX9。');
  process.exit(1);
}